"""add performance snapshots"""
revision = 'a1634ee503fa'
down_revision = 'bdcdfb406a72'
branch_labels = None
depend_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    """Apply upgrade migrations."""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('asset_value', sa.Float(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('asset_pair', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_id'), 'performance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_timestamp'), 'performance_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse upgrade migrations."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_snapshots_timestamp'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    # ### end Alembic commands ###
