"""add_strategy_health_fields"""
revision = 'bdcdfb406a72'
down_revision = 'd105dca196c2'
branch_labels = None
depend_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    """Apply upgrade migrations."""
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('health_status', sa.String(length=50), nullable=True))
    op.add_column('strategies', sa.Column('pending_adjustment_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse upgrade migrations."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'pending_adjustment_json')
    op.drop_column('strategies', 'health_status')
    # ### end Alembic commands ###
